version: '3'

services:

  db:
    image: mysql:8.0

    container_name: MySQL-container
    ports:
    - "3306:3306"
    environment:
     MYSQL_ROOT_PASSWORD: root
     MYSQL_DATABASE: user
     MYSQL_PASSWORD: root
    healthcheck:
     test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
     interval: 10s
     retries: 5
     timeout: 5s

  backend:
    build: ./backend
    container_name: Go-container
    ports:
      - "8000:8000"
    depends_on:
       db:
        condition: service_healthy
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=user

  frontend:
    build: ./frontend
    container_name: vue-container
    ports:
      - "8080:8080" 
    depends_on:
      - backend
